# Minimal Tab bar styling 
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

## customizations
enabled_layouts      splits:split_axis=horizontal
scrollback_lines     2000

# keymaps
map ctrl+t            new_tab_with_cwd
map ctrl+c            copy_or_interrupt
map ctrl+v            paste_from_clipboard
map ctrl+]            launch --location=vsplit --cwd=current
map ctrl+[            launch --location=hsplit --cwd=current
map ctrl+shift+/      kitten keymap.py
map ctrl+shift+`      kitty_shell window
map ctrl+shift+q      close_window_with_confirmation ignore-shell

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
# input_delay 0
# repaint_delay 2
# sync_to_monitor no
# wayland_enable_ime no
